// <auto-generated />
namespace ALZAGRO.AppRendicionGastos.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ReplacePaymentTypeWithAliquotAndMoreChanges : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ReplacePaymentTypeWithAliquotAndMoreChanges));
        
        string IMigrationMetadata.Id
        {
            get { return "201810111733391_ReplacePaymentTypeWithAliquotAndMoreChanges"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
